### PR TITLE
v1.0.2 add automate deletion, two new env for Jira issue creation

### LINKED ISSUE #12: Uppercase all sequencers doesn't work now due to directory naming change
https://github.com/eastgenomics/ansible-run-monitoring/blob/20c98a3732ff85cfb80d60394f989788ef815010/main.py#L28

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- added deletion in main script
- two env for Jira issue creation - `JIRA_PROJECT_ID` and `JIRA_REPORTER_ID`
- remove sending mail function to helpdesk
- removed envs related to mailing helpdesk
- added if clause in `post_msg_to_slack` function to filter incoming msg before sending to Slack

# Fix
#12
#11 

# Unit Test
```
jason@jason-ThinkPad-T14-Gen-2i:~/github/ansible-run-monitoring$ docker run --env-file /home/jason/github/ansible-run-monitoring/.env ansible:test
Error while retrieving session configuration: AttributeError: 'NoneType'
object has no attribute 'pid'
..2022-10-06 15:55:17,822:util log:util:INFO:Clear pickle
.2022-10-06 15:55:17,823:util log:util:ERROR:/invisible_directory not found
.2022-10-06 15:55:18,048:util log:util:ERROR:The token could not be found, code 401. Request Time=1665071717.9290001, Request ID=unavailable
.....2022-10-06 15:55:18,918:util log:util:INFO:Loop through A01295a started
2022-10-06 15:55:18,919:util log:util:INFO:1 folders in A01295a detected
2022-10-06 15:55:18,919:util log:util:INFO:1 logs in A01295a detected
...
----------------------------------------------------------------------
Ran 12 tests in 5.395s

OK
```
# Notification on stale runs
Screenshot from 2022-11-24 17-30-03

# Alert on to-be-deleted runs
Screenshot from 2022-11-24 17-29-55

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 2 of 9 files reviewed, 19 unresolved discussions (waiting on @JasonLing95)

___
*[`main.py` line 97 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGR5HC0meq7FNnZ4-e:-NEGR5HC0meq7FNnZ4-f:b-qvulcv) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L97)):*
can we add a sense check here with an assert or similar that `seq` and `run` are non empty? Else the path will evaluate to just the genetic_dir parent and delete everything:
```
jethro@jethro-T490:/tmp$ mkdir -p test/sub_test
jethro@jethro-T490:/tmp$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> GENETIC_DIR="test"
>>> seq=""
>>> run=""
>>> f'{GENETIC_DIR}/{seq}/{run}'
'test//'
>>> shutil.rmtree(f'{GENETIC_DIR}/{seq}/{run}')
>>> 
```



_Code quote:_
```Python
shutil.rmtree(f'{GENETIC_DIR}/{seq}/{run}')
```
___
*[`main.py` line 128 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGRmBmDqOxJW86eXT9:-NEGRmBmDqOxJW86eXTA:b-29o28g) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L128)):*
> ```Python
>             p_usage = shutil.disk_usage(GENETIC_DIR)
>             # make datetime into str type
>             j_date = today.strftime('%d/%m/%Y')
> ```

what are the `p_` and `j_` prefixes?



_Code quote:_
```Python
            p_usage = shutil.disk_usage(GENETIC_DIR)
            # make datetime into str type
            j_date = today.strftime('%d/%m/%Y')
```
___
*[`main.py` line 140 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGSLPiB8RIa8yQS_o0:-NEGSLPiB8RIa8yQS_o1:b9pohem) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L140)):*
you're not using `status` here are you? This can just be a list comp:
```
>>> d={'a':'one', 'b':'two', 'c':'three'}
>>> [f"{k} in /genetics/{v}" for k, v in d.items()]
['a in /genetics/one', 'b in /genetics/two', 'c in /genetics/three']
```



_Code quote:_
```Python
            # format deleted run for issue description
            for k, v in tmp_delete.items():
                seq = v['seq']
                status = v['status']

                j_data.append(






                    f'{k} in /genetics/{seq}'
                )
```
___
*[`main.py` line 178 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGStD79tewciG4Mulp:-NEGStD8EZ_l1gCAWxtV:btl2wb5) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L178)):*
> ```Python
>                 False)
> 
>             if 'id' in response:
> ```

why checking for `id`? can you not use `response.ok`? (I've no idea what is in the response though) 



_Code quote:_
```Python
if 'id' in response:
```
___
*[`main.py` line 193 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGT9981EILD_2nzfMv:-NEGT9981EILD_2nzfMw:b5xp4y4) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L193)):*
> ```Python
>                 sys.exit('END SCRIPT')
> 
>     elif today.day == 24:
> ```

would these be better as a fixed day instead of date? (i.e. delete on first monday of the month, send alert on 3rd monday of the month).

just thinking if the 24th is a saturday the notification may be missed and it may be deleting data we don't want to



_Code quote:_
```Python
elif today.day == 24:
```
___
*[`README.md` line 3 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGUN3S69LyhhZ8GcMh:-NEGUN3S69LyhhZ8GcMi:b6vxnx) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L3)):*
> ```Markdown
> # Ansible Run Monitoring
> 
> Script to automate deletion of qualified runs in `/genetics` and notifying of stale runs. An alert will be sent to Slack before the deletion.
> ```

can you define what a stale run is?



_Code quote:_
```Markdown
stale runs
```
___
*[`README.md` line 3 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGURkF2pVIuUMcJzLN:-NEGURkF2pVIuUMcJzLO:b36iokm) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L3)):*
> ```Markdown
> # Ansible Run Monitoring
> 
> Script to automate deletion of qualified runs in `/genetics` and notifying of stale runs. An alert will be sent to Slack before the deletion.
> ```

deletion of local sequencing data from the server running dx-streaming-upload to stream data into DNAnexus



_Code quote:_
```Markdown
of qualified runs in `/genetics`
```
___
*[`README.md` line 9 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGToEf0vfJfmQWUHsG:-NEGToEf0vfJfmQWUHsH:b-2jymcc) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L9)):*
> ```Markdown
> - Script will be scheduled to run every day by cron
> - Compile list of runs in `/genetics`
> - To qualify for automated deletion, each runs need to fulfill four main criterias: 
> ```

criteria



_Code quote:_
```Markdown
criterias
```
___
*[`README.md` line 11 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGTvWVBmWDiHW27R4c:-NEGTvWVBmWDiHW27R4d:baki4ns) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L11)):*
> ```Markdown
> - To qualify for automated deletion, each runs need to fulfill four main criterias: 
>   - 002 project on DNANexus
>   - Runs on `staging52`
> ```

`001_Staging_Area52` DNAnexus project



_Code quote:_
```Markdown
`staging52`
```
___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGUsksBeqjBYCVvE6R:-NEGUsksBeqjBYCVvE6S:b-al22r8) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L34)):*
> ```Markdown
> - `HTTP_PROXY`: http proxy
> - `HTTPS_PROXY`: https proxy
> - `ANSIBLE_WEEK `: number of week old (e.g. 6)
> ```

number of weeks for what?



_Code quote:_
```Markdown
number of week old (
```
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGV1s42OQPBBTGnA0F:-NEGV1s42OQPBBTGnA0G:btbiuqy) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L45)):*
> ```Markdown
> - `SLACK_TOKEN`: slack auth token
> - `JIRA_PROJECT_ID`: Jira project id (helpdesk id e.g. EBHD, EBH)
> - `JIRA_REPORTER_ID`: Jira reporter id for raising issue
> ```

whats the reporter ID?



_Code quote:_
```Markdown
reporter id
```
___
*[`bin/jira.py` line 3 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGVC5J8NV3EQf84uH2:-NEGVC5J8NV3EQf84uH3:bnxuarn) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/jira.py#L3)):*
> ```Python
> """
> Jira Class as wrapper for Jira API request
> EBH -
> ```

needed? feels like it should be in the confluence docs



_Code quote:_
```Python
EBH -
EBHD 10042
```
___
*[`bin/jira.py` line 31 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGVIcs52S86jQZmowf:-NEGVIcs52S86jQZmowg:b-ieuwjq) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/jira.py#L31)):*
> ```Python
>     """
>     def __init__(self, data):
>         if data is not None:
> ```

this can just be `if data:` can't it?



_Code quote:_
```Python
if data is not None:
```
___
*[`bin/jira.py` line 183 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGVhlm0CuYdLLts_xG:-NEGVhln09IltYd_Lsv9:bgqz1ji) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/jira.py#L183)):*
> ```Python
>         issues = response.json()['values']
> 
>         while response.json()['isLastPage'] is False:
> ```

if there's an error should we not be checking for this in the response? something like I did for conductor maybe:

```
        start = 0
        response_data = []

        while True:
            response = self.http.get(
                url=f"{self.queue_url}/issue?start={start}",
                headers=self.headers,
                auth=self.auth
            )

            if not response.ok:
                # handle the error
                ...
            else:
                response = response.json()

            if response['size'] == 0:
                break

            response_data.extend(response['values'])
            start += 50
``` 



_Code quote:_
```Python
while response.json()['isLastPage'] is False:
```
___
*[`bin/util.py` line 175 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGX9EmDX0Wr-fmhbgh:-NEGX9EmDX0Wr-fmhbgi:bb6l55x) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L175)):*
> ```Python
>         else:
>             # chunk data based on its length after '\n'.join()
>             # if > than 7,995 after join(), we append
> ```

7700



_Code quote:_
```Python
7,995
```
___
*[`bin/util.py` line 294 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGXILd2-qF8ih8TUSA:-NEGXILd2-qF8ih8TUSB:bb7oqyl) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L294)):*
> ```Python
>     """
> 
>     # should return sth if there's a file
> ```

sth?



_Code quote:_
```Python
sth
```
___
*[`bin/util.py` line 301 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGXd-04FpkDJe9-Aqr:-NEGXd-04FpkDJe9-Aqs:bihcbui) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L301)):*
> ```Python
>         folder=f'/{directory}')
> 
>     if dx_obj is not None:
> ```

`if dx_obj:`



_Code quote:_
```Python
f dx_obj is not None
```
___
*[`bin/util.py` line 327 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGXz6u0YlU-_letyil:-NEGXz6u0YlU-_letyim:b-u0q8jo) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L327)):*
> ```Python
>     """
> 
>     dxes = list(dx.search.find_projects(
> ```

weird variable name, can you stick to just `response` or `projects` I guess for this since you're directly casting to a list, minor thing but it makes it easier to read (especially in other functions where its referenced further down the function)



_Code quote:_
```Python
dxes
```
___
*[`bin/util.py` line 463 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGZKE46TE9SpMxwFfj:-NEGZKE46TE9SpMxwFfk:beky189) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L463)):*
any reason to not use `shutil.disk_usage()` to get size of a directory?

```
>>> disk_usage('/home/jethro')
usage(total=500609097728, used=420772102144, free=54332272640)
```



_Code quote:_
```Python
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_size(entry.path)
    return round(total / 1024 / 1024 / 1024, 2)
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 193 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGT9981EILD_2nzfMv:-NEk8hqp8dI-FJHrBf1c:bdzd5qc) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/main.py#L193)):*
> Automated deletion of runs from ansible server

updated
___
*[`main.py` line 119 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjLC8dBNGKhp7noo64:-NEk9lsj-D7EcmtCBcfi:bbd0z85) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L119)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could we make this error more verbose ? something like:

```
msg = (
    f"ANSIBLE-MONITORING: ERROR with deleting run {run}.
    "Stopping automatic deletion of further runs."
    f"\n```{err}```"
)
```
</blockquote></details>

edited message
___
*[`main.py` line 168 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjNoGWEuf8nMgCqj55:-NEk9n8A4vXYNGUz4dtq:b-9ig9gq) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L168)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

it can also make it easier to read if you define inputs in the function call, also ensures none of them are the wrong way round. It's hard when code reviewing as there's no intellisense info type box on hovering to know what the function is (for standard library functions this is fine as you usuall know what it does, for local ones its harder), i.e.
```
jira.create_issue(
    summary=f'{jira_date} Deleted Runs In 10.252.166.184',
    issue_id=10124,
    project_id=JIRA_PROJECT_ID,
    .....
```
I just find this more readable, feel free to disagree and ignore though
</blockquote></details>

i agree with you. added inputs to all post_message_to_slack and jira call
___
*[`main.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjN6pd8d7fHTimLjj7:-NEk9supAfMBlj2M_Li-:b-n9tkhd) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L169)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

IP could change in the future if IT change things, could this just be something like "Automated deletion of runs from ansible server"
</blockquote></details>

changed
___
*[`main.py` line 279 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjS7eUExk3QpsMES_k:-NEk8jUq9LQgU1ZtJTu1:b-c9v4mh) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L279)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

in general you should use `.replace()` over strip unless you _really_ want to delete those characters as strip removes any of those characters up until one doesn't match and not against a pattern, e.g.g:
```
>>> project = "project-pabc"
>>> project.lstrip('project-')
'abc'
>>> project.replace('project-', '')
'pabc'
```

here it stripped off the `p` from the ID, so if the project ID has any character at the beginning in `project-` it will be removed
</blockquote></details>

changed to replace instead of lstrip
___
*[`main.py` line 288 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjT5Ch3vdrpyqyM6dr:-NEk8lzR6W2HUp-GVX_6:b-wvzwlk) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L288)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this seems too indented, this might be better:
```
if (
    status.upper() == 'ALL SAMPLES RELEASED' and
    assay in JIRA_ASSAY
):
```
</blockquote></details>

changed indentation
___
*[`main.py` line 321 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjVC9A8quGnz1shOC2:-NEk8oLw2tV242LfsbJj:b-2ng1ql) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L321)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this comment is confusing, is it meant to be both?
</blockquote></details>

yes it meant both. changed & to 'and'
___
*[`main.py` line 341 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEjRXhVCcGh2r9INfzv:-NEk8rSn24Kajl3NcTvy:b-7ql1td) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/c1b740475003aa5fd7487a1d3d0d3b807e309cc3/main.py#L341)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

typo
</blockquote></details>

fixed
___
*[`README.md` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGV1s42OQPBBTGnA0F:-NEk8sPA44H4DcVWKgBZ:b-1hvofd) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/README.md#L45)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I think Matt is going to make an Atlassian account for automation things, just fyi we should be then able to use that when we deploy so its will be created from that user
</blockquote></details>

ok, the reporter-id can be changed in the config so once that's created, I could change it in the config
___
*[`bin/jira.py` line 183 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGVhlm0CuYdLLts_xG:-NEk8y9L5sEreRuA78SB:b-7tmbp4) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/jira.py#L183)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if there's an error with the response will this just continue now its a break? does anything need to be done?
</blockquote></details>

the function is not used by the main script but just there so that if we need it in the future for debug / something, we can use it. I added raise Exception and printing the response.

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 3 of 9 files reviewed, 11 unresolved discussions (waiting on @jethror1)

___
*[`bin/util.py` line 463 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEGZKE46TE9SpMxwFfj:-NEkABD45NHTjAucADX7:b32vhw) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/018ff73d412c770c50e623f0fcd01e14e3664c75/bin/util.py#L463)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ahh okay, makes sense
</blockquote></details>

:)

**Comment by JasonLing95** [comment]
# Jira acknowledgement ticket
https://cuhbioinformatics.atlassian.net/browse/EBHD-618?atlOrigin=eyJpIjoiMGQ3Y2RjOTcwYTdhNDdhODk3NzA4ZDI1NzViNzhmM2EiLCJwIjoiaiJ9

**Comment by JasonLing95** [comment]
# Stale Run Notification
Screenshot from 2022-11-01 16-09-27

# Deletion Alert Notification 
Screenshot from 2022-11-01 16-09-35

# Deletion of Run but Run not there Notification
Screenshot from 2022-11-01 16-09-37

**Comment by JasonLing95** [comment]
Mock Run write up: https://cuhbioinformatics.atlassian.net/l/cp/DrHEYZN5

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`main.py` line 127 at r3](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEktQTq1LDMWb5khao_:-NEktQTq1LDMWb5khaoa:bjrly31) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/dc27cc2e91f8bc17d8d02332630edf5444a90e6e/main.py#L127)):*
> ```Python
>                     clear_memory(ANSIBLE_PICKLE)
> 
>                     msg = (
> ```

minor formatting for this based off screenshot :
- add warning symbol before `ANSIBLE-MONITORING`
- add `\n` after first sentence
- add backticks around `{run}`

if there's more alerts being sent to slack maybe add the warning symbol as a prefix in the slack notification function based off the channel being sent to



_Code quote:_
```Python
                    msg = (
                        f"ANSIBLE-MONITORING: ERROR with deleting {run}."
                        "Stopping further automatic deletion."
                        f"\n```{e}```"
                    )
```
___
*[`bin/util.py` line 146 at r3](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEku2hN8Ei5E0_xNbxG:-NEku2hN8Ei5E0_xNbxH:bpk7vft) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/dc27cc2e91f8bc17d8d02332630edf5444a90e6e/bin/util.py#L146)):*
> ```Python
>             pretext = (
>                 ':warning: ansible-run-monitoring: '
>                 f'{data_count} runs that *WILL BE DELETED* on {today}\n'
> ```

can we make the date bold so it stands out



_Code quote:_
```Python
{today}
```

**Comment by JasonLing95** [comment]
- added bold to date
- fixed week showing with decimal
- added warning icon to alert message
Screenshot from 2022-11-01 17-07-42
Screenshot from 2022-11-01 17-07-33

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 127 at r3](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEktQTq1LDMWb5khao_:-NFo9eJ5ANj1iPG-cP6a:bsitw26) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/dc27cc2e91f8bc17d8d02332630edf5444a90e6e/main.py#L127)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

minor formatting for this based off screenshot :
- add warning symbol before `ANSIBLE-MONITORING`
- add `\n` after first sentence
- add backticks around `{run}`

if there's more alerts being sent to slack maybe add the warning symbol as a prefix in the slack notification function based off the channel being sent to
</blockquote></details>

Edited
___
*[`bin/util.py` line 146 at r3](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13#-NEku2hN8Ei5E0_xNbxG:-NFo9gk_1tB4TRVlEzGC:b-qgt8wo) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/dc27cc2e91f8bc17d8d02332630edf5444a90e6e/bin/util.py#L146)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can we make the date bold so it stands out
</blockquote></details>

Added bold to date. Added example screenshot in PR

**Review by jethror1 — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
