### PR TITLE
minor code change

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- Added env DEBUG
- Added more comments
- `check_project_directory` function now check /processed directory in staging52
- changes to how script read directories (e.g. A01295a, A01295b, A01303a). In the future, just add more sequencer in `.env`

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9)

### CODE REVIEW

**Comment by JasonLing95** [comment]
https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`main.py` line 33 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gAbNf9qzn2wdooiR5:-N9gAbNf9qzn2wdooiR6:bivslov) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L33)):*
> ```Python
>         log.info('Running in PRODUCTION mode')
> 
>     if dx_login(DNANEXUS_TOKEN):
> ```

could this just be 

```
if not dx_login(DNANEXUS_TOKEN):
        message = "ANSIBLE-MONITORING: ERROR with dxpy login!"
        post_message_to_slack('egg-alerts', message, DEBUG)
```



_Code quote:_
```Python
    if dx_login(DNANEXUS_TOKEN):
        pass
    else:
```
___
*[`main.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gAo018vccJ_z7dlUu:-N9gAo018vccJ_z7dlUv:bgitcrv) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L41)):*
> ```Python
>         sys.exit()
> 
>     if directory_check([GENETIC_DIR, LOGS_DIR]):
> ```

same as above to use `not`



_Code quote:_
```Python
    if directory_check([GENETIC_DIR, LOGS_DIR]):
        pass
    else:
```
___
*[`main.py` line 72 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gB4hG9_cPyMwmWlEz:-N9gB4hG9_cPyMwmWlF-:b-sjqgl6) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L72)):*
is this to remove all the suffixes from the files? if so it will break if any files don't have a `.`:

```
>>> s='string'
>>> s.split('.')[1].strip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

maybe something like this would be better:
```
>>> from pathlib import PurePath
>>> s1='string'
>>> s2='string2_with_suffixes.tar.gz'
>>> s1.replace(''.join(PurePath(s1).suffixes), '')
'string'
>>> s2.replace(''.join(PurePath(s2).suffixes), '')
'string2_with_suffixes'
```



_Code quote:_
```Python
x.split('.')[1].strip() for x in os.listdir(logs_dir)
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 33 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gAbNf9qzn2wdooiR5:-N9gNLmRB-jvn_MC9wCX:b-rcu9aq) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L33)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

could this just be 

```
if not dx_login(DNANEXUS_TOKEN):
        message = "ANSIBLE-MONITORING: ERROR with dxpy login!"
        post_message_to_slack('egg-alerts', message, DEBUG)
```
</blockquote></details>

edited
___
*[`main.py` line 41 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gAo018vccJ_z7dlUu:-N9gNMuh5qJa3pjctjEy:b-rcu9aq) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L41)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above to use `not`
</blockquote></details>

edited
___
*[`main.py` line 72 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9#-N9gB4hG9_cPyMwmWlEz:-N9gNNwFB8oGWzbanUPD:bpba8q5) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/2807278aa9fc2c205ff8773031b5642216cf8d21/main.py#L72)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this to remove all the suffixes from the files? if so it will break if any files don't have a `.`:

```
>>> s='string'
>>> s.split('.')[1].strip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

maybe something like this would be better:
```
>>> from pathlib import PurePath
>>> s1='string'
>>> s2='string2_with_suffixes.tar.gz'
>>> s1.replace(''.join(PurePath(s1).suffixes), '')
'string'
>>> s2.replace(''.join(PurePath(s2).suffixes), '')
'string2_with_suffixes'
```
</blockquote></details>

no, it's just that the log files in /var/log/dx-streaming-upload in ansible server is formatted as such 'run.220114_A01295_0044_BHV5JFDRXY.lane.all.log'  and we are just getting the middle part (project name)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
