### PR TITLE
v1.1.0 - bonus changes

### PR DESCRIPTION
**Pull request by jethror1**
- added final check for path to run directory to delete being valid to guard against deleting parent
- minor formatting
- remove unused import

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33)

### CODE REVIEW

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`monitor.py` line 429 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33#-NtSkEka9f6X4tJ4X9cG:-NtSkEka9f6X4tJ4X9cH:b466mt9) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/20e53b53523661c55b5f9b30590c549f9e4d3c4c/monitor.py#L429)):*
> ```Python
>             post_simple_message_to_slack(
>                 message=error,
>                 channel="egg-test",
> ```

should this be egg-alerts?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`monitor.py` line 429 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33#-NtSkEka9f6X4tJ4X9cG:-NtSlUxR5tkd59w_V1dE:b-fvqrvl) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/20e53b53523661c55b5f9b30590c549f9e4d3c4c/monitor.py#L429)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

should this be egg-alerts?
</blockquote></details>

ah yes, changed it. Might switch all the channels to an env variable in another PR to make it easy to switch between testing and prod

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by JasonLing95 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
