### PR TITLE
v1.0.3 exclude Jira ticket that's not Sequencing

### LINKED ISSUE #19: If multiple runs detected, ignore Query type ticket

### PR DESCRIPTION
**Pull request by JasonLing95**
- separate `test_jira` out from `test_util`
- some reformat
- `mock.py` now generate a text file that list runs that's bound to be deleted

Fix #19

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20)

### CODE REVIEW

**Comment by JasonLing95** [comment]
Unit Test
```
(env) jason@jason-ThinkPad-T14-Gen-2i:~/github/ansible-run-monitoring$ docker run --env-file /home/jason/github/ansible-run-monitoring/.env ansible:test
....2023-03-08 15:08:24,373:util log:util:INFO:Clear pickle
.2023-03-08 15:08:24,374:util log:util:ERROR:/invisible_directory not found
...2023-03-08 15:08:24,666:util log:util:ERROR:The token could not be found, code 401. Request Time=1678288104.4845195, Request ID=unavailable
...2023-03-08 15:08:25,791:util log:util:INFO:Loop through A01295a started
2023-03-08 15:08:25,792:util log:util:INFO:1 folders in A01295a detected
2023-03-08 15:08:25,792:util log:util:INFO:1 logs in A01295a detected
...
----------------------------------------------------------------------
Ran 14 tests in 6.336s

OK
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`mock.py` line 246 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20#-NQPEwsoEwByuKJIjXYW:-NQPEwspA3wykc9noUBr:b51zyyl) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/660c75b25df701a4c46716cbf500fb1713a21ce3/mock.py#L246)):*
> ```Python
>     f.write(f'today: {today}\n')
>     f.write(f'stale cutt-off: {stale_date}\n')
>     f.write(f'old enough cut-off: {old_date}\n')
> ```

same here as below comment



_Code quote:_
```Python
    f.write(f'today: {today}\n')
    f.write(f'stale cutt-off: {stale_date}\n')
    f.write(f'old enough cut-off: {old_date}\n')
```
___
*[`mock.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20#-NQPEKcRAPjE5Rar5_ne:-NQPEKcRAPjE5Rar5_nf:b-37qj0z) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/660c75b25df701a4c46716cbf500fb1713a21ce3/mock.py#L256)):*
> ```Python
>         f.write(f'{row}\n')
> 
>     f.write('\n')
> ```

any reason for this not to just be a single `write()` call like:
```
f.write(
    '\n**run the script with datetime set to 1st of any month\n'
    'we should expect those runs above that PASS be deleted\n'
    'and acknowledgement Jira ticket should show up on EBHD\n'
)
```



_Code quote:_
```Python
    f.write('\n')

    f.write('**run the script with datetime set to 1st of any month\n')
    f.write('we should expect those runs above that PASS be deleted\n')
    f.write('and acknowledgement Jira ticket should show up on EBHD\n')
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`mock.py` line 246 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20#-NQPEwsoEwByuKJIjXYW:-NQPF_D-450WWQEDBUxy:b-fq6oay) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/660c75b25df701a4c46716cbf500fb1713a21ce3/mock.py#L246)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

same here as below comment
</blockquote></details>

Personal preference
___
*[`mock.py` line 256 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20#-NQPEKcRAPjE5Rar5_ne:-NQPFYKt5Ne7rwgdNSbU:bv78297) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/660c75b25df701a4c46716cbf500fb1713a21ce3/mock.py#L256)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

any reason for this not to just be a single `write()` call like:
```
f.write(
    '\n**run the script with datetime set to 1st of any month\n'
    'we should expect those runs above that PASS be deleted\n'
    'and acknowledgement Jira ticket should show up on EBHD\n'
)
```
</blockquote></details>

No reason. Personal preference

**Review by jethror1 — APPROVED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
